create database economico;
use economico;

CREATE TABLE socio_economico (
    Id				INT UNSIGNED NOT NULL auto_increment PRIMARY KEY,
    Nome			VARCHAR(255),
    Idade			INT,
    Genero			VARCHAR(255),
    Escolaridade	VARCHAR(255),
    Ocupacao		VARCHAR(255),
    Renda_Mensal	VARCHAR(255),
    Estado_Civil	VARCHAR(255),
    Estado			VARCHAR(255),
    Cidade			VARCHAR(255)
);

INSERT INTO socio_economico (Nome, Idade, Genero, Escolaridade, Ocupacao, Renda_Mensal, Estado_Civil, Estado, Cidade) VALUES
	('Valentina Sales', '75', 'Feminino', 'Médio Completo', 'CLT', '3 a 5 SM', 'Viúvo', 'RS', 'Correia'),
	('Luiz Gustavo Caldeira', '19', 'Feminino', 'Superior Completo', 'CLT', '3 a 5 SM', 'Viúvo', 'MG', 'Fernandes de Duarte'),
	('Dr. Fernando da Mata', '69', 'Masculino', 'Pós-graduação', 'Servidor Público', '1 a 2 SM', 'Divorciado', 'PE', 'da Rocha das Flores'),
	('Dr. Joaquim Farias', '38', 'Feminino', 'Superior Incompleto', 'Desempregado', '< 1 SM', 'Solteiro', 'RS', 'Campos da Prata'),
	('Nicolas Freitas', '30', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '< 1 SM', 'Divorciado', 'PA', 'Cardoso do Campo'),
	('Diogo Alves', '37', 'Masculino', 'Superior Incompleto', 'Desempregado', '2 a 3 SM', 'Divorciado', 'CE', 'da Rocha'),
	('Otávio Novaes', '42', 'Feminino', 'Fundamental Completo', 'Desempregado', '> 10 SM', 'Solteiro', 'MG', 'Ferreira'),
	('Pedro Lucas da Cruz', '28', 'Masculino', 'Médio Completo', 'Desempregado', '2 a 3 SM', 'Viúvo', 'BA', 'Caldeira'),
	('Gabrielly Ribeiro', '63', 'Masculino', 'Pós-graduação', 'CLT', '< 1 SM', 'Divorciado', 'MA', 'Barbosa'),
	('Isaac Lopes', '75', 'Feminino', 'Superior Completo', 'Autônomo', '2 a 3 SM', 'Viúvo', 'RS', 'Rodrigues'),
	('Ana Sophia Silveira', '68', 'Feminino', 'Fundamental Incompleto', 'Aposentado', '5 a 10 SM', 'Viúvo', 'PE', 'Lopes'),
	('Ana Julia Castro', '50', 'Feminino', 'Pós-graduação', 'Empresário', '5 a 10 SM', 'Viúvo', 'PA', 'Duarte do Norte'),
	('Dra. Clara Cardoso', '21', 'Feminino', 'Fundamental Incompleto', 'Servidor Público', '3 a 5 SM', 'Viúvo', 'CE', 'Nunes de Minas'),
	('Diogo Cardoso', '20', 'Feminino', 'Pós-graduação', 'Servidor Público', '> 10 SM', 'Solteiro', 'SP', 'Cavalcanti de Viana'),
	('Danilo Monteiro', '61', 'Masculino', 'Superior Incompleto', 'Servidor Público', '2 a 3 SM', 'Solteiro', 'PA', 'Dias'),
	('Vinicius Gonçalves', '79', 'Feminino', 'Fundamental Completo', 'Autônomo', '1 a 2 SM', 'Viúvo', 'BA', 'Moraes'),
	('Rebeca Mendes', '46', 'Masculino', 'Médio Completo', 'Aposentado', '< 1 SM', 'Solteiro', 'CE', 'Costela da Mata'),
	('Catarina Cavalcanti', '57', 'Masculino', 'Superior Completo', 'Desempregado', '3 a 5 SM', 'Divorciado', 'MG', 'Gonçalves'),
	('Davi Lucca Alves', '52', 'Masculino', 'Pós-graduação', 'CLT', '1 a 2 SM', 'Solteiro', 'SP', 'da Luz da Praia'),
	('Emanuella Cardoso', '67', 'Feminino', 'Fundamental Completo', 'Aposentado', '< 1 SM', 'Viúvo', 'PA', 'Souza de Nunes'),
	('Clarice Melo', '50', 'Feminino', 'Fundamental Completo', 'CLT', '1 a 2 SM', 'Casado', 'PE', 'Rodrigues de Farias'),
	('Sra. Rafaela da Conceição', '48', 'Masculino', 'Fundamental Incompleto', 'CLT', '> 10 SM', 'Divorciado', 'PR', 'Rodrigues do Galho'),
	('Stephany Moreira', '34', 'Feminino', 'Superior Completo', 'Empresário', '1 a 2 SM', 'Viúvo', 'PR', 'da Cruz do Galho'),
	('Maria Julia da Conceição', '53', 'Masculino', 'Fundamental Incompleto', 'Autônomo', '5 a 10 SM', 'Casado', 'RJ', 'Pires de Minas'),
	('Luiz Henrique Mendes', '42', 'Feminino', 'Fundamental Completo', 'CLT', '3 a 5 SM', 'Solteiro', 'PR', 'Correia de da Mata'),
	('Leonardo Farias', '79', 'Masculino', 'Superior Completo', 'Desempregado', '1 a 2 SM', 'Viúvo', 'RJ', 'da Mata do Sul'),
	('Dr. Vitor Gonçalves', '45', 'Feminino', 'Pós-graduação', 'CLT', '2 a 3 SM', 'Divorciado', 'SP', 'Fogaça de da Cunha'),
	('Sra. Valentina Rodrigues', '37', 'Feminino', 'Fundamental Completo', 'Desempregado', '2 a 3 SM', 'Casado', 'PR', 'Silveira de da Rocha'),
	('Maria Cecília Nogueira', '75', 'Feminino', 'Superior Incompleto', 'CLT', '3 a 5 SM', 'Solteiro', 'PR', 'Pinto da Serra'),
	('Sr. João Guilherme Teixeira', '19', 'Feminino', 'Superior Incompleto', 'CLT', '< 1 SM', 'Viúvo', 'SP', 'Melo de Goiás'),
	('Davi Lucca da Cruz', '21', 'Feminino', 'Fundamental Completo', 'Autônomo', '2 a 3 SM', 'Solteiro', 'BA', 'Ramos'),
	('Valentina Duarte', '73', 'Feminino', 'Superior Completo', 'Autônomo', '1 a 2 SM', 'Casado', 'PE', 'Fogaça'),
	('Luiza Dias', '18', 'Masculino', 'Fundamental Completo', 'Autônomo', '5 a 10 SM', 'Divorciado', 'SP', 'Carvalho Grande'),
	('Lavínia Cardoso', '66', 'Masculino', 'Superior Completo', 'Empresário', '5 a 10 SM', 'Casado', 'MG', 'Lima do Campo'),
	('Maria Alice da Costa', '35', 'Masculino', 'Superior Completo', 'Autônomo', '1 a 2 SM', 'Divorciado', 'PR', 'Lima'),
	('Isabelly Rezende', '39', 'Feminino', 'Superior Incompleto', 'Servidor Público', '1 a 2 SM', 'Solteiro', 'CE', 'Gonçalves'),
	('Ana Carolina Sales', '19', 'Feminino', 'Fundamental Completo', 'Autônomo', '2 a 3 SM', 'Divorciado', 'PE', 'da Costa'),
	('Maitê da Conceição', '45', 'Masculino', 'Médio Incompleto', 'Desempregado', '2 a 3 SM', 'Casado', 'RS', 'da Mota de Nogueira'),
	('Ana Júlia Costela', '26', 'Feminino', 'Fundamental Incompleto', 'Aposentado', '< 1 SM', 'Casado', 'PR', 'Freitas'),
	('Brenda Azevedo', '60', 'Masculino', 'Pós-graduação', 'Desempregado', '< 1 SM', 'Viúvo', 'PE', 'da Costa Verde'),
	('Maria Vitória da Costa', '35', 'Feminino', 'Médio Completo', 'Aposentado', '> 10 SM', 'Viúvo', 'MG', 'Rocha'),
	('Juliana Lopes', '21', 'Feminino', 'Superior Completo', 'Desempregado', '1 a 2 SM', 'Casado', 'MA', 'Santos'),
	('João Pedro Fernandes', '61', 'Masculino', 'Médio Incompleto', 'Aposentado', '1 a 2 SM', 'Solteiro', 'MG', 'Farias das Flores'),
	('Enzo Gabriel Freitas', '41', 'Feminino', 'Médio Completo', 'CLT', '1 a 2 SM', 'Solteiro', 'RJ', 'Azevedo das Flores'),
	('Pedro Miguel Caldeira', '63', 'Masculino', 'Pós-graduação', 'Desempregado', '3 a 5 SM', 'Casado', 'CE', 'Caldeira de Correia'),
	('Kamilly das Neves', '64', 'Masculino', 'Superior Completo', 'Desempregado', '< 1 SM', 'Solteiro', 'PE', 'Duarte da Praia'),
	('Ana Luiza Fernandes', '35', 'Feminino', 'Pós-graduação', 'Servidor Público', '> 10 SM', 'Divorciado', 'MA', 'Melo de Goiás'),
	('Francisco Carvalho', '36', 'Feminino', 'Médio Incompleto', 'Desempregado', '1 a 2 SM', 'Casado', 'PA', 'Nascimento de Jesus'),
	('Sr. Lucca Pereira', '55', 'Feminino', 'Superior Completo', 'Autônomo', '5 a 10 SM', 'Divorciado', 'MG', 'Cardoso'),
	('Daniel das Neves', '72', 'Masculino', 'Fundamental Completo', 'Servidor Público', '< 1 SM', 'Divorciado', 'PE', 'Teixeira'),
	('Maria Fernanda da Costa', '37', 'Feminino', 'Médio Completo', 'Desempregado', '5 a 10 SM', 'Viúvo', 'PR', 'Fernandes da Praia'),
	('Samuel da Paz', '51', 'Masculino', 'Superior Completo', 'Servidor Público', '> 10 SM', 'Divorciado', 'PE', 'da Mata dos Dourados'),
	('João Lucas Nogueira', '19', 'Masculino', 'Pós-graduação', 'Empresário', '> 10 SM', 'Solteiro', 'CE', 'da Conceição'),
	('Melissa Nunes', '64', 'Feminino', 'Superior Incompleto', 'Aposentado', '< 1 SM', 'Divorciado', 'MA', 'Novaes'),
	('Raquel Freitas', '68', 'Feminino', 'Superior Incompleto', 'CLT', '1 a 2 SM', 'Solteiro', 'MG', 'da Rosa do Norte'),
	('Vicente Correia', '68', 'Feminino', 'Fundamental Incompleto', 'CLT', '1 a 2 SM', 'Casado', 'MG', 'Araújo do Amparo'),
	('João Felipe Ramos', '42', 'Masculino', 'Fundamental Completo', 'CLT', '1 a 2 SM', 'Viúvo', 'MA', 'Barros das Pedras'),
	('Leonardo Silveira', '24', 'Feminino', 'Fundamental Completo', 'Desempregado', '1 a 2 SM', 'Viúvo', 'PE', 'Cunha do Galho'),
	('Cauê Barros', '55', 'Masculino', 'Médio Incompleto', 'Autônomo', '2 a 3 SM', 'Solteiro', 'CE', 'Ferreira da Prata'),
	('Levi da Rosa', '48', 'Feminino', 'Superior Incompleto', 'Autônomo', '5 a 10 SM', 'Divorciado', 'BA', 'da Costa'),
	('Gustavo Henrique Lima', '54', 'Feminino', 'Fundamental Completo', 'CLT', '5 a 10 SM', 'Viúvo', 'PA', 'Caldeira Paulista'),
	('Arthur Porto', '80', 'Feminino', 'Superior Incompleto', 'CLT', '2 a 3 SM', 'Viúvo', 'MG', 'da Conceição da Praia'),
	('Srta. Maitê da Rocha', '30', 'Feminino', 'Médio Incompleto', 'CLT', '> 10 SM', 'Divorciado', 'CE', 'da Cunha da Prata'),
	('Juan Alves', '27', 'Masculino', 'Superior Incompleto', 'Servidor Público', '2 a 3 SM', 'Viúvo', 'RS', 'Peixoto das Pedras'),
	('Enrico Nascimento', '60', 'Masculino', 'Médio Incompleto', 'Desempregado', '5 a 10 SM', 'Casado', 'RJ', 'Oliveira de Cardoso'),
	('Gustavo Correia', '19', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '5 a 10 SM', 'Viúvo', 'SP', 'Campos do Sul'),
	('Diego da Rosa', '54', 'Masculino', 'Fundamental Incompleto', 'CLT', '3 a 5 SM', 'Casado', 'BA', 'Duarte'),
	('Breno Moraes', '61', 'Feminino', 'Fundamental Completo', 'Empresário', '3 a 5 SM', 'Divorciado', 'PE', 'da Costa das Pedras'),
	('João Pedro Cunha', '32', 'Masculino', 'Pós-graduação', 'Aposentado', '3 a 5 SM', 'Viúvo', 'RJ', 'Moreira de Minas'),
	('Srta. Camila Gonçalves', '50', 'Masculino', 'Superior Incompleto', 'CLT', '1 a 2 SM', 'Solteiro', 'PR', 'da Cruz de Peixoto'),
	('Evelyn Fogaça', '76', 'Masculino', 'Superior Completo', 'CLT', '2 a 3 SM', 'Solteiro', 'PE', 'das Neves do Sul'),
	('Maysa da Cunha', '44', 'Masculino', 'Fundamental Incompleto', 'Aposentado', '3 a 5 SM', 'Solteiro', 'MA', 'da Cruz dos Dourados'),
	('João da Paz', '30', 'Feminino', 'Superior Completo', 'CLT', '3 a 5 SM', 'Solteiro', 'BA', 'Ferreira'),
	('Calebe Correia', '61', 'Feminino', 'Médio Incompleto', 'Empresário', '< 1 SM', 'Divorciado', 'PR', 'Melo'),
	('Davi Mendes', '45', 'Masculino', 'Fundamental Completo', 'Desempregado', '> 10 SM', 'Divorciado', 'PR', 'Fogaça'),
	('Thomas Mendes', '51', 'Masculino', 'Pós-graduação', 'Autônomo', '5 a 10 SM', 'Casado', 'PR', 'Porto'),
	('Nina Oliveira', '51', 'Feminino', 'Fundamental Incompleto', 'CLT', '> 10 SM', 'Viúvo', 'MA', 'Duarte Alegre'),
	('Emilly Moreira', '35', 'Masculino', 'Pós-graduação', 'Autônomo', '3 a 5 SM', 'Solteiro', 'RS', 'Aragão da Prata'),
	('Nathan Rodrigues', '33', 'Masculino', 'Médio Incompleto', 'Servidor Público', '3 a 5 SM', 'Divorciado', 'BA', 'Souza'),
	('Francisco Aragão', '32', 'Feminino', 'Fundamental Incompleto', 'CLT', '2 a 3 SM', 'Viúvo', 'BA', 'Gonçalves da Mata'),
	('Guilherme Lima', '35', 'Masculino', 'Pós-graduação', 'Aposentado', '1 a 2 SM', 'Viúvo', 'MG', 'Farias'),
	('Srta. Luana Dias', '50', 'Feminino', 'Pós-graduação', 'Servidor Público', '5 a 10 SM', 'Solteiro', 'MA', 'Barros da Mata'),
	('Lívia Souza', '35', 'Masculino', 'Superior Completo', 'Desempregado', '1 a 2 SM', 'Solteiro', 'SP', 'Nunes'),
	('Yago Pires', '55', 'Masculino', 'Superior Completo', 'Aposentado', '> 10 SM', 'Casado', 'MG', 'Rocha da Prata'),
	('Guilherme Aragão', '34', 'Masculino', 'Superior Incompleto', 'Autônomo', '1 a 2 SM', 'Casado', 'RJ', 'da Conceição'),
	('Vitória Fernandes', '22', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '< 1 SM', 'Solteiro', 'PA', 'Lopes do Sul'),
	('Sr. Henrique Carvalho', '49', 'Masculino', 'Fundamental Completo', 'Servidor Público', '1 a 2 SM', 'Casado', 'RS', 'Nogueira Verde'),
	('Levi Dias', '67', 'Masculino', 'Pós-graduação', 'Empresário', '3 a 5 SM', 'Solteiro', 'RS', 'da Costa'),
	('Helena da Cunha', '58', 'Feminino', 'Fundamental Incompleto', 'Aposentado', '3 a 5 SM', 'Viúvo', 'BA', 'Cardoso de Rezende'),
	('Isabella Costa', '57', 'Feminino', 'Fundamental Completo', 'CLT', '> 10 SM', 'Viúvo', 'PA', 'Mendes'),
	('Pedro Henrique Mendes', '72', 'Masculino', 'Superior Incompleto', 'Aposentado', '5 a 10 SM', 'Divorciado', 'MA', 'Fogaça'),
	('João Pedro Carvalho', '42', 'Masculino', 'Fundamental Completo', 'Servidor Público', '< 1 SM', 'Viúvo', 'BA', 'Fogaça da Praia'),
	('Maria Vitória Melo', '30', 'Masculino', 'Superior Incompleto', 'Desempregado', '3 a 5 SM', 'Casado', 'SP', 'Martins'),
	('Noah Moraes', '50', 'Masculino', 'Fundamental Incompleto', 'Autônomo', '< 1 SM', 'Divorciado', 'CE', 'Duarte'),
	('Noah Ferreira', '61', 'Feminino', 'Superior Incompleto', 'CLT', '3 a 5 SM', 'Casado', 'PE', 'Vieira'),
	('Srta. Clara Cunha', '47', 'Feminino', 'Médio Completo', 'Aposentado', '> 10 SM', 'Divorciado', 'RJ', 'Silveira'),
	('Diego Barbosa', '54', 'Feminino', 'Médio Completo', 'Aposentado', '3 a 5 SM', 'Divorciado', 'SP', 'da Rocha'),
	('Vitor Moura', '29', 'Masculino', 'Médio Completo', 'Desempregado', '2 a 3 SM', 'Casado', 'RJ', 'da Luz da Prata'),
	('Isadora da Paz', '64', 'Masculino', 'Superior Incompleto', 'CLT', '3 a 5 SM', 'Casado', 'BA', 'Teixeira de Goiás'),
	('Maria Luiza da Mota', '27', 'Masculino', 'Superior Completo', 'Empresário', '5 a 10 SM', 'Solteiro', 'PA', 'Martins'),
	('Vinicius da Paz', '75', 'Masculino', 'Médio Incompleto', 'Aposentado', '< 1 SM', 'Solteiro', 'CE', 'Costela'),
	('Milena Oliveira', '33', 'Masculino', 'Superior Incompleto', 'Autônomo', '2 a 3 SM', 'Casado', 'MG', 'da Rocha Verde'),
	('João Vitor Rocha', '66', 'Feminino', 'Superior Completo', 'Servidor Público', '> 10 SM', 'Divorciado', 'RJ', 'Mendes'),
	('Dra. Heloísa Teixeira', '57', 'Masculino', 'Pós-graduação', 'CLT', '< 1 SM', 'Viúvo', 'PA', 'Fernandes Verde'),
	('Pietra Cunha', '23', 'Feminino', 'Médio Completo', 'Desempregado', '5 a 10 SM', 'Casado', 'PA', 'Farias da Prata'),
	('Cecília da Rosa', '33', 'Masculino', 'Médio Completo', 'Autônomo', '1 a 2 SM', 'Viúvo', 'MA', 'Farias'),
	('Noah Azevedo', '67', 'Masculino', 'Médio Incompleto', 'Autônomo', '2 a 3 SM', 'Viúvo', 'PE', 'Nunes da Prata'),
	('Noah Silva', '47', 'Masculino', 'Pós-graduação', 'Empresário', '1 a 2 SM', 'Viúvo', 'RS', 'Castro de Pires'),
	('Maria Sophia Moreira', '66', 'Feminino', 'Fundamental Completo', 'Desempregado', '3 a 5 SM', 'Divorciado', 'CE', 'Cardoso'),
	('Júlia da Cruz', '30', 'Masculino', 'Médio Incompleto', 'Servidor Público', '3 a 5 SM', 'Divorciado', 'RJ', 'Barbosa'),
	('Leandro Almeida', '39', 'Masculino', 'Fundamental Incompleto', 'Autônomo', '5 a 10 SM', 'Viúvo', 'PA', 'da Cunha Grande'),
	('Davi Lucas da Cruz', '58', 'Feminino', 'Fundamental Completo', 'CLT', '5 a 10 SM', 'Solteiro', 'MG', 'da Paz de Castro'),
	('Sr. João Guilherme Gomes', '78', 'Masculino', 'Fundamental Completo', 'Desempregado', '3 a 5 SM', 'Divorciado', 'SP', 'da Conceição Verde'),
	('Amanda Nunes', '68', 'Masculino', 'Médio Incompleto', 'CLT', '2 a 3 SM', 'Casado', 'BA', 'Silveira de Duarte'),
	('Heloísa da Conceição', '27', 'Feminino', 'Fundamental Completo', 'CLT', '2 a 3 SM', 'Casado', 'SP', 'Carvalho'),
	('Sarah da Rosa', '66', 'Masculino', 'Superior Incompleto', 'Empresário', '2 a 3 SM', 'Viúvo', 'RS', 'Cavalcanti'),
	('Srta. Isadora Viana', '24', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '3 a 5 SM', 'Solteiro', 'BA', 'Mendes'),
	('Anthony Dias', '80', 'Masculino', 'Médio Completo', 'Aposentado', '5 a 10 SM', 'Casado', 'PA', 'Carvalho'),
	('Pietro Lima', '43', 'Feminino', 'Superior Completo', 'Aposentado', '< 1 SM', 'Solteiro', 'CE', 'da Cunha de Cardoso'),
	('Dra. Ana Vitória Barros', '36', 'Feminino', 'Pós-graduação', 'CLT', '> 10 SM', 'Viúvo', 'SP', 'da Luz Paulista'),
	('Kamilly Cardoso', '71', 'Masculino', 'Médio Incompleto', 'Aposentado', '3 a 5 SM', 'Divorciado', 'MA', 'Lopes'),
	('Mirella Duarte', '34', 'Feminino', 'Superior Incompleto', 'Empresário', '< 1 SM', 'Viúvo', 'PR', 'Souza'),
	('Maysa Mendes', '44', 'Feminino', 'Médio Completo', 'Servidor Público', '< 1 SM', 'Viúvo', 'RJ', 'Jesus'),
	('Fernanda Gomes', '63', 'Feminino', 'Fundamental Incompleto', 'CLT', '1 a 2 SM', 'Divorciado', 'RJ', 'Ramos'),
	('Ana Sophia da Mota', '60', 'Feminino', 'Fundamental Incompleto', 'Empresário', '1 a 2 SM', 'Divorciado', 'RS', 'Porto Verde'),
	('Milena Campos', '42', 'Feminino', 'Superior Completo', 'Desempregado', '3 a 5 SM', 'Solteiro', 'RJ', 'da Mota de da Rosa'),
	('Matheus Ramos', '69', 'Feminino', 'Pós-graduação', 'CLT', '2 a 3 SM', 'Viúvo', 'BA', 'Peixoto das Flores'),
	('Breno Caldeira', '35', 'Masculino', 'Superior Completo', 'Desempregado', '3 a 5 SM', 'Casado', 'SP', 'Dias Verde'),
	('Cauã Peixoto', '78', 'Masculino', 'Médio Incompleto', 'Aposentado', '1 a 2 SM', 'Divorciado', 'BA', 'Peixoto de Freitas'),
	('Ana Monteiro', '26', 'Masculino', 'Médio Completo', 'Desempregado', '> 10 SM', 'Divorciado', 'RJ', 'Pereira'),
	('Juliana Dias', '24', 'Masculino', 'Fundamental Incompleto', 'Servidor Público', '3 a 5 SM', 'Divorciado', 'CE', 'Nascimento das Flores'),
	('Gustavo Henrique da Mata', '19', 'Masculino', 'Pós-graduação', 'Aposentado', '< 1 SM', 'Divorciado', 'PR', 'Cardoso'),
	('Marcos Vinicius Farias', '39', 'Masculino', 'Fundamental Incompleto', 'Empresário', '3 a 5 SM', 'Divorciado', 'PE', 'Rodrigues'),
	('Elisa Barbosa', '51', 'Masculino', 'Médio Completo', 'Aposentado', '2 a 3 SM', 'Viúvo', 'BA', 'Almeida Alegre'),
	('Isadora Aragão', '66', 'Feminino', 'Fundamental Incompleto', 'Servidor Público', '> 10 SM', 'Viúvo', 'RS', 'Correia'),
	('Thomas Almeida', '62', 'Masculino', 'Superior Completo', 'Autônomo', '3 a 5 SM', 'Viúvo', 'RS', 'Mendes do Norte'),
	('Luiz Henrique Araújo', '26', 'Masculino', 'Fundamental Incompleto', 'Empresário', '5 a 10 SM', 'Casado', 'CE', 'Novaes dos Dourados'),
	('Breno Pereira', '67', 'Feminino', 'Fundamental Incompleto', 'Servidor Público', '1 a 2 SM', 'Divorciado', 'CE', 'Cardoso de Teixeira'),
	('Dr. Pedro Lucas Moraes', '61', 'Masculino', 'Superior Completo', 'Servidor Público', '2 a 3 SM', 'Viúvo', 'PR', 'da Cruz do Galho'),
	('Theo Moura', '29', 'Masculino', 'Superior Completo', 'Aposentado', '5 a 10 SM', 'Solteiro', 'PR', 'Freitas'),
	('Kamilly Duarte', '26', 'Masculino', 'Médio Incompleto', 'Empresário', '5 a 10 SM', 'Viúvo', 'SP', 'Alves da Praia'),
	('Vitor Hugo Martins', '49', 'Masculino', 'Superior Completo', 'Aposentado', '3 a 5 SM', 'Divorciado', 'PE', 'Fogaça de Minas'),
	('Murilo Pinto', '38', 'Masculino', 'Fundamental Completo', 'Autônomo', '< 1 SM', 'Casado', 'RS', 'da Paz'),
	('Giovanna da Mota', '31', 'Feminino', 'Médio Incompleto', 'CLT', '< 1 SM', 'Solteiro', 'PE', 'Rocha'),
	('Benjamin da Mata', '52', 'Feminino', 'Médio Completo', 'Empresário', '5 a 10 SM', 'Casado', 'PA', 'Nascimento'),
	('Vicente das Neves', '24', 'Masculino', 'Médio Incompleto', 'CLT', '> 10 SM', 'Viúvo', 'BA', 'Rodrigues da Serra'),
	('Alice Farias', '35', 'Masculino', 'Pós-graduação', 'Desempregado', '> 10 SM', 'Viúvo', 'SP', 'da Costa do Galho'),
	('Lara Barbosa', '75', 'Masculino', 'Fundamental Incompleto', 'Aposentado', '> 10 SM', 'Casado', 'SP', 'Novaes'),
	('Dr. João Moura', '55', 'Masculino', 'Médio Incompleto', 'CLT', '5 a 10 SM', 'Solteiro', 'PE', 'Melo'),
	('Srta. Gabriela Gomes', '70', 'Feminino', 'Médio Completo', 'Aposentado', '> 10 SM', 'Viúvo', 'PE', 'Castro'),
	('Elisa Porto', '71', 'Masculino', 'Pós-graduação', 'Aposentado', '> 10 SM', 'Solteiro', 'MA', 'Costela das Pedras'),
	('Helena Dias', '26', 'Feminino', 'Superior Completo', 'Autônomo', '> 10 SM', 'Divorciado', 'RJ', 'Jesus da Prata'),
	('Srta. Juliana Duarte', '38', 'Feminino', 'Superior Incompleto', 'Autônomo', '1 a 2 SM', 'Solteiro', 'RJ', 'Rezende do Sul'),
	('Vitor Gabriel Freitas', '74', 'Masculino', 'Médio Incompleto', 'Empresário', '> 10 SM', 'Solteiro', 'PA', 'da Mata de Vieira'),
	('Luiza Barros', '68', 'Feminino', 'Médio Completo', 'Empresário', '> 10 SM', 'Casado', 'CE', 'Pinto de Nunes'),
	('Rafaela Cardoso', '41', 'Feminino', 'Superior Completo', 'Aposentado', '< 1 SM', 'Casado', 'PE', 'Rezende'),
	('Olivia Silva', '24', 'Masculino', 'Superior Completo', 'Desempregado', '1 a 2 SM', 'Viúvo', 'RS', 'Fernandes'),
	('Mirella Melo', '55', 'Masculino', 'Médio Completo', 'Servidor Público', '3 a 5 SM', 'Solteiro', 'BA', 'Monteiro de da Paz'),
	('Srta. Emanuelly Vieira', '27', 'Masculino', 'Superior Incompleto', 'Autônomo', '> 10 SM', 'Solteiro', 'RJ', 'Castro do Amparo'),
	('Fernando da Mota', '47', 'Feminino', 'Fundamental Completo', 'Empresário', '5 a 10 SM', 'Divorciado', 'MG', 'Costa de Fernandes'),
	('Ana Julia Silveira', '29', 'Feminino', 'Fundamental Completo', 'CLT', '1 a 2 SM', 'Viúvo', 'BA', 'Caldeira de Monteiro'),
	('Milena Costela', '41', 'Masculino', 'Fundamental Completo', 'Empresário', '3 a 5 SM', 'Casado', 'PE', 'Rodrigues Paulista'),
	('Ana Vitória Araújo', '66', 'Masculino', 'Pós-graduação', 'Empresário', '3 a 5 SM', 'Solteiro', 'RJ', 'Vieira de Fogaça'),
	('Stella Cunha', '28', 'Masculino', 'Médio Completo', 'CLT', '5 a 10 SM', 'Viúvo', 'RJ', 'Ferreira Verde'),
	('Rafael Pereira', '33', 'Feminino', 'Superior Incompleto', 'Empresário', '1 a 2 SM', 'Casado', 'RJ', 'Silva das Flores'),
	('Ana Vitória Sales', '24', 'Masculino', 'Fundamental Completo', 'Desempregado', '5 a 10 SM', 'Solteiro', 'PA', 'Jesus'),
	('Caroline da Rocha', '61', 'Masculino', 'Pós-graduação', 'Empresário', '> 10 SM', 'Divorciado', 'BA', 'Costa'),
	('Sophie Lopes', '41', 'Feminino', 'Superior Completo', 'Servidor Público', '5 a 10 SM', 'Divorciado', 'MA', 'da Costa Verde'),
	('Pedro Miguel Correia', '29', 'Masculino', 'Fundamental Incompleto', 'Aposentado', '2 a 3 SM', 'Viúvo', 'RJ', 'Cardoso'),
	('Kamilly Silveira', '46', 'Masculino', 'Superior Completo', 'Servidor Público', '> 10 SM', 'Solteiro', 'RJ', 'Oliveira de Campos'),
	('Ryan Costela', '29', 'Masculino', 'Superior Incompleto', 'CLT', '5 a 10 SM', 'Divorciado', 'MA', 'Cardoso'),
	('Dra. Sophia Fernandes', '49', 'Feminino', 'Médio Completo', 'Empresário', '1 a 2 SM', 'Viúvo', 'SP', 'Lima de Lopes'),
	('Sra. Maria Clara Pinto', '22', 'Masculino', 'Médio Completo', 'Empresário', '3 a 5 SM', 'Casado', 'BA', 'Correia'),
	('João Gonçalves', '71', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '2 a 3 SM', 'Casado', 'PR', 'Melo'),
	('Sofia Melo', '68', 'Masculino', 'Médio Incompleto', 'Autônomo', '1 a 2 SM', 'Viúvo', 'PA', 'Ribeiro dos Dourados'),
	('Nicolas Ramos', '41', 'Feminino', 'Fundamental Completo', 'Aposentado', '< 1 SM', 'Divorciado', 'RJ', 'Melo'),
	('Luiz Henrique Araújo', '36', 'Masculino', 'Pós-graduação', 'Desempregado', '5 a 10 SM', 'Divorciado', 'CE', 'da Mata da Mata'),
	('Dr. Vitor Gabriel Azevedo', '67', 'Masculino', 'Médio Completo', 'Aposentado', '5 a 10 SM', 'Solteiro', 'RJ', 'da Cruz'),
	('Ian da Cunha', '67', 'Feminino', 'Superior Incompleto', 'CLT', '1 a 2 SM', 'Divorciado', 'RJ', 'Aragão'),
	('Paulo Viana', '39', 'Masculino', 'Pós-graduação', 'Servidor Público', '> 10 SM', 'Solteiro', 'PE', 'Correia Verde'),
	('Beatriz Cunha', '45', 'Feminino', 'Médio Incompleto', 'Autônomo', '2 a 3 SM', 'Divorciado', 'RJ', 'Almeida'),
	('Giovanna Pereira', '47', 'Masculino', 'Superior Incompleto', 'Autônomo', '5 a 10 SM', 'Viúvo', 'SP', 'Silva de Barros'),
	('Manuela da Mota', '65', 'Masculino', 'Superior Incompleto', 'Empresário', '< 1 SM', 'Solteiro', 'PR', 'Mendes'),
	('Francisco Gonçalves', '58', 'Feminino', 'Médio Completo', 'Servidor Público', '5 a 10 SM', 'Divorciado', 'PA', 'da Rocha da Prata'),
	('Valentina Pereira', '30', 'Masculino', 'Médio Incompleto', 'CLT', '> 10 SM', 'Solteiro', 'PE', 'das Neves da Prata'),
	('Ryan Duarte', '71', 'Masculino', 'Superior Completo', 'Aposentado', '3 a 5 SM', 'Solteiro', 'PE', 'Gonçalves de Barbosa'),
	('Marcos Vinicius da Rosa', '69', 'Masculino', 'Fundamental Incompleto', 'CLT', '3 a 5 SM', 'Viúvo', 'MA', 'Azevedo do Oeste'),
	('Maysa da Paz', '78', 'Masculino', 'Fundamental Incompleto', 'Aposentado', '1 a 2 SM', 'Viúvo', 'MG', 'Duarte'),
	('Thomas Pires', '69', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '< 1 SM', 'Divorciado', 'RJ', 'Ramos'),
	('Gabrielly Barros', '41', 'Masculino', 'Pós-graduação', 'Desempregado', '2 a 3 SM', 'Solteiro', 'MA', 'Pereira de Sales'),
	('Sophia Nascimento', '55', 'Feminino', 'Superior Incompleto', 'Servidor Público', '1 a 2 SM', 'Divorciado', 'CE', 'Carvalho'),
	('Pedro Miguel da Rosa', '45', 'Feminino', 'Fundamental Completo', 'CLT', '> 10 SM', 'Casado', 'PA', 'Fogaça'),
	('Marcelo da Rocha', '25', 'Masculino', 'Fundamental Incompleto', 'Aposentado', '3 a 5 SM', 'Divorciado', 'PA', 'da Rosa da Serra'),
	('Dra. Milena Silva', '58', 'Feminino', 'Médio Incompleto', 'Aposentado', '3 a 5 SM', 'Divorciado', 'PR', 'Moura do Campo'),
	('João Gabriel Alves', '52', 'Masculino', 'Fundamental Completo', 'Desempregado', '> 10 SM', 'Divorciado', 'RJ', 'Caldeira Verde'),
	('Mariane Gonçalves', '23', 'Masculino', 'Pós-graduação', 'Aposentado', '3 a 5 SM', 'Solteiro', 'RS', 'Barbosa da Mata'),
	('Srta. Sofia Oliveira', '37', 'Masculino', 'Médio Incompleto', 'Autônomo', '3 a 5 SM', 'Divorciado', 'PA', 'Cunha'),
	('Mariane Pereira', '34', 'Masculino', 'Médio Completo', 'Desempregado', '5 a 10 SM', 'Divorciado', 'RS', 'Duarte do Galho'),
	('Rodrigo da Cunha', '61', 'Masculino', 'Fundamental Completo', 'Empresário', '< 1 SM', 'Casado', 'PE', 'Ribeiro da Mata'),
	('Kevin Nogueira', '31', 'Masculino', 'Superior Incompleto', 'Aposentado', '5 a 10 SM', 'Viúvo', 'RJ', 'Fernandes'),
	('Luiz Henrique Teixeira', '42', 'Masculino', 'Superior Completo', 'Servidor Público', '3 a 5 SM', 'Divorciado', 'BA', 'Barbosa'),
	('Pietra das Neves', '57', 'Masculino', 'Superior Incompleto', 'Empresário', '< 1 SM', 'Casado', 'PA', 'Barbosa'),
	('Dr. Pedro Henrique Viana', '19', 'Masculino', 'Pós-graduação', 'Aposentado', '3 a 5 SM', 'Solteiro', 'PE', 'Castro do Amparo'),
	('Dra. Ana Araújo', '44', 'Feminino', 'Superior Incompleto', 'Empresário', '3 a 5 SM', 'Casado', 'RS', 'Silva dos Dourados'),
	('Eloah Moreira', '67', 'Masculino', 'Superior Completo', 'Aposentado', '3 a 5 SM', 'Viúvo', 'MG', 'Nunes Verde'),
	('Arthur Porto', '78', 'Feminino', 'Médio Incompleto', 'Desempregado', '5 a 10 SM', 'Divorciado', 'PR', 'Freitas'),
	('Amanda Monteiro', '48', 'Masculino', 'Superior Incompleto', 'Empresário', '> 10 SM', 'Viúvo', 'RJ', 'Barbosa Verde'),
	('Ana Sophia Monteiro', '26', 'Feminino', 'Fundamental Completo', 'Autônomo', '> 10 SM', 'Viúvo', 'SP', 'Vieira do Amparo'),
	('Juliana Dias', '59', 'Feminino', 'Pós-graduação', 'CLT', '< 1 SM', 'Casado', 'PE', 'Barros'),
	('Lucas Vieira', '70', 'Feminino', 'Pós-graduação', 'Desempregado', '5 a 10 SM', 'Casado', 'PE', 'Moreira Paulista'),
	('Giovanna Nogueira', '24', 'Masculino', 'Pós-graduação', 'Aposentado', '> 10 SM', 'Solteiro', 'PR', 'Cardoso'),
	('Stephany Souza', '65', 'Masculino', 'Médio Completo', 'Aposentado', '< 1 SM', 'Casado', 'MG', 'da Rocha'),
	('Sra. Mirella Cardoso', '70', 'Masculino', 'Superior Incompleto', 'Aposentado', '2 a 3 SM', 'Solteiro', 'PR', 'Rezende de da Luz'),
	('Agatha Cunha', '51', 'Masculino', 'Superior Completo', 'CLT', '> 10 SM', 'Casado', 'PE', 'Oliveira de Cardoso'),
	('Dr. Paulo Oliveira', '79', 'Feminino', 'Pós-graduação', 'Empresário', '2 a 3 SM', 'Viúvo', 'RJ', 'Nogueira'),
	('Lucas Souza', '35', 'Masculino', 'Superior Incompleto', 'CLT', '1 a 2 SM', 'Solteiro', 'BA', 'Moraes das Flores'),
	('Emilly Rocha', '37', 'Masculino', 'Pós-graduação', 'CLT', '5 a 10 SM', 'Viúvo', 'RJ', 'Vieira de Minas'),
	('Ana Clara Nunes', '26', 'Feminino', 'Médio Incompleto', 'CLT', '1 a 2 SM', 'Casado', 'PE', 'Porto do Campo'),
	('Ana Clara Caldeira', '80', 'Masculino', 'Fundamental Incompleto', 'Desempregado', '< 1 SM', 'Solteiro', 'CE', 'Santos'),
	('Maria Sophia Ribeiro', '23', 'Masculino', 'Médio Incompleto', 'Aposentado', '2 a 3 SM', 'Solteiro', 'RS', 'Oliveira'),
	('Sophia da Cunha', '44', 'Masculino', 'Pós-graduação', 'Autônomo', '1 a 2 SM', 'Divorciado', 'PA', 'Cardoso'),
	('Bryan da Mata', '33', 'Feminino', 'Fundamental Completo', 'Desempregado', '3 a 5 SM', 'Viúvo', 'BA', 'Cardoso'),
	('Kaique da Cruz', '31', 'Feminino', 'Fundamental Incompleto', 'Autônomo', '5 a 10 SM', 'Casado', 'PA', 'da Rocha'),
	('Ana Carolina Cunha', '27', 'Feminino', 'Pós-graduação', 'Desempregado', '< 1 SM', 'Viúvo', 'MG', 'Ribeiro do Norte'),
	('Yuri Santos', '59', 'Feminino', 'Superior Completo', 'Empresário', '3 a 5 SM', 'Casado', 'RS', 'Novaes do Campo'),
	('Julia Barros', '27', 'Masculino', 'Pós-graduação', 'Empresário', '< 1 SM', 'Viúvo', 'RJ', 'Costela'),
	('Enzo Gabriel Aragão', '67', 'Feminino', 'Superior Completo', 'Empresário', '> 10 SM', 'Divorciado', 'PE', 'Oliveira de da Luz'),
	('Alice Campos', '74', 'Masculino', 'Médio Completo', 'Aposentado', '> 10 SM', 'Solteiro', 'MA', 'Moreira'),
	('Lorenzo Jesus', '42', 'Masculino', 'Pós-graduação', 'CLT', '3 a 5 SM', 'Solteiro', 'BA', 'Gonçalves'),
	('Sra. Emanuella Melo', '20', 'Masculino', 'Superior Incompleto', 'Autônomo', '< 1 SM', 'Casado', 'RS', 'Nascimento do Galho'),
	('Otávio Silveira', '79', 'Feminino', 'Pós-graduação', 'CLT', '< 1 SM', 'Casado', 'RS', 'Porto de Goiás'),
	('Sr. Ian Vieira', '73', 'Feminino', 'Superior Completo', 'CLT', '2 a 3 SM', 'Viúvo', 'SP', 'Caldeira'),
	('Marcelo Silveira', '60', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '1 a 2 SM', 'Solteiro', 'SP', 'Fogaça'),
	('Heitor Ramos', '65', 'Masculino', 'Médio Incompleto', 'Aposentado', '< 1 SM', 'Solteiro', 'MG', 'Aragão'),
	('Amanda Rocha', '48', 'Masculino', 'Médio Incompleto', 'Aposentado', '< 1 SM', 'Solteiro', 'SP', 'Souza Verde'),
	('Lucca Cardoso', '22', 'Masculino', 'Fundamental Completo', 'Servidor Público', '< 1 SM', 'Divorciado', 'MG', 'Cunha de Gomes'),
	('Sr. Leandro da Paz', '58', 'Masculino', 'Superior Completo', 'CLT', '2 a 3 SM', 'Divorciado', 'PR', 'Costela de Rezende'),
	('Samuel Gonçalves', '71', 'Masculino', 'Superior Incompleto', 'CLT', '< 1 SM', 'Divorciado', 'CE', 'Mendes do Campo'),
	('João Vitor Moraes', '39', 'Feminino', 'Fundamental Incompleto', 'Empresário', '1 a 2 SM', 'Casado', 'MA', 'Santos'),
	('Thomas Freitas', '47', 'Feminino', 'Superior Incompleto', 'Servidor Público', '5 a 10 SM', 'Solteiro', 'BA', 'da Paz Paulista'),
	('Bianca Silveira', '73', 'Masculino', 'Médio Completo', 'Aposentado', '> 10 SM', 'Solteiro', 'MG', 'Carvalho de Farias'),
	('Emanuelly Carvalho', '47', 'Masculino', 'Superior Incompleto', 'Empresário', '< 1 SM', 'Divorciado', 'CE', 'Costa Grande'),
	('Dr. Felipe Dias', '47', 'Feminino', 'Médio Completo', 'Empresário', '5 a 10 SM', 'Divorciado', 'RS', 'da Mota'),
	('Renan Peixoto', '33', 'Feminino', 'Superior Completo', 'Empresário', '> 10 SM', 'Casado', 'PA', 'Ramos'),
	('Sr. Vitor das Neves', '39', 'Feminino', 'Superior Completo', 'Autônomo', '3 a 5 SM', 'Divorciado', 'PE', 'Farias'),
	('Gabriela Lopes', '36', 'Feminino', 'Superior Incompleto', 'Desempregado', '5 a 10 SM', 'Casado', 'BA', 'Cavalcanti'),
	('Murilo Teixeira', '78', 'Masculino', 'Superior Completo', 'Autônomo', '1 a 2 SM', 'Viúvo', 'MG', 'Novaes dos Dourados'),
	('Valentina da Rosa', '34', 'Feminino', 'Superior Completo', 'Desempregado', '3 a 5 SM', 'Viúvo', 'RJ', 'Melo'),
	('Carlos Eduardo Campos', '45', 'Masculino', 'Médio Completo', 'CLT', '< 1 SM', 'Viúvo', 'PA', 'Freitas do Galho'),
	('Clarice Ferreira', '65', 'Masculino', 'Pós-graduação', 'Servidor Público', '< 1 SM', 'Divorciado', 'CE', 'Almeida'),
	('Thales Porto', '41', 'Feminino', 'Médio Completo', 'Aposentado', '2 a 3 SM', 'Casado', 'PE', 'Nogueira de Campos'),
	('Breno da Cunha', '23', 'Feminino', 'Superior Completo', 'Aposentado', '3 a 5 SM', 'Casado', 'PE', 'Peixoto'),
	('Felipe Costa', '71', 'Feminino', 'Fundamental Incompleto', 'Aposentado', '> 10 SM', 'Solteiro', 'MG', 'Nogueira'),
	('Sr. Erick Teixeira', '58', 'Feminino', 'Superior Incompleto', 'Desempregado', '5 a 10 SM', 'Solteiro', 'BA', 'Cardoso'),
	('Samuel Araújo', '37', 'Masculino', 'Fundamental Completo', 'CLT', '> 10 SM', 'Viúvo', 'MA', 'da Cruz da Prata'),
	('Sr. Pedro Henrique Melo', '74', 'Feminino', 'Médio Incompleto', 'CLT', '> 10 SM', 'Divorciado', 'PE', 'Cardoso'),
	('Ana Cardoso', '41', 'Feminino', 'Superior Completo', 'CLT', '3 a 5 SM', 'Casado', 'PA', 'Moreira de Cunha'),
	('Caio da Cruz', '68', 'Feminino', 'Pós-graduação', 'Desempregado', '3 a 5 SM', 'Solteiro', 'RJ', 'da Conceição de Silveira'),
	('Pietra Peixoto', '32', 'Masculino', 'Superior Completo', 'Empresário', '3 a 5 SM', 'Solteiro', 'PA', 'Teixeira de Araújo'),
	('Ana Laura Nunes', '79', 'Masculino', 'Superior Incompleto', 'Autônomo', '< 1 SM', 'Casado', 'SP', 'Nunes de Castro'),
	('Thiago Pereira', '49', 'Masculino', 'Superior Incompleto', 'CLT', '2 a 3 SM', 'Solteiro', 'RS', 'Araújo'),
	('Sr. Diego Souza', '46', 'Masculino', 'Fundamental Completo', 'Desempregado', '< 1 SM', 'Solteiro', 'CE', 'Carvalho'),
	('Sra. Sophie Mendes', '63', 'Feminino', 'Fundamental Completo', 'Empresário', '1 a 2 SM', 'Divorciado', 'CE', 'Aragão de Aragão'),
	('Carolina Pires', '66', 'Feminino', 'Superior Completo', 'Empresário', '2 a 3 SM', 'Divorciado', 'RS', 'Araújo'),
	('Melissa Lima', '76', 'Feminino', 'Superior Incompleto', 'Aposentado', '3 a 5 SM', 'Solteiro', 'PA', 'Ramos de Vieira'),
	('Diego Alves', '30', 'Masculino', 'Fundamental Completo', 'Aposentado', '1 a 2 SM', 'Solteiro', 'PE', 'Porto de Oliveira'),
	('Laura Ribeiro', '28', 'Feminino', 'Superior Completo', 'Desempregado', '> 10 SM', 'Divorciado', 'CE', 'Caldeira'),
	('Sophie Sales', '46', 'Masculino', 'Pós-graduação', 'Aposentado', '1 a 2 SM', 'Solteiro', 'MA', 'Gonçalves'),
	('Dr. Davi Luiz Ribeiro', '23', 'Masculino', 'Fundamental Completo', 'Autônomo', '1 a 2 SM', 'Divorciado', 'MG', 'Freitas'),
	('Srta. Catarina Pinto', '41', 'Feminino', 'Médio Completo', 'Aposentado', '< 1 SM', 'Divorciado', 'MA', 'Moreira Paulista'),
	('Pietro Novaes', '28', 'Masculino', 'Superior Completo', 'Autônomo', '2 a 3 SM', 'Viúvo', 'CE', 'Rezende Paulista'),
	('Guilherme Barros', '34', 'Feminino', 'Pós-graduação', 'CLT', '2 a 3 SM', 'Solteiro', 'SP', 'Barbosa'),
	('Kevin Dias', '36', 'Feminino', 'Pós-graduação', 'Aposentado', '2 a 3 SM', 'Divorciado', 'BA', 'Vieira'),
	('Davi Correia', '69', 'Feminino', 'Pós-graduação', 'CLT', '5 a 10 SM', 'Divorciado', 'RS', 'da Cruz'),
	('Cecília Gonçalves', '24', 'Masculino', 'Pós-graduação', 'Aposentado', '> 10 SM', 'Viúvo', 'MA', 'da Luz do Sul'),
	('Sofia Rezende', '58', 'Feminino', 'Superior Completo', 'Servidor Público', '3 a 5 SM', 'Divorciado', 'RS', 'das Neves de Jesus'),
	('Antônio da Mota', '25', 'Masculino', 'Pós-graduação', 'CLT', '> 10 SM', 'Viúvo', 'PA', 'das Neves'),
	('Manuela da Costa', '43', 'Masculino', 'Médio Incompleto', 'CLT', '1 a 2 SM', 'Divorciado', 'BA', 'Rocha do Norte'),
	('Igor Almeida', '70', 'Masculino', 'Médio Incompleto', 'Aposentado', '5 a 10 SM', 'Casado', 'BA', 'Moraes do Campo'),
	('Ryan Azevedo', '59', 'Feminino', 'Médio Incompleto', 'Desempregado', '> 10 SM', 'Casado', 'PR', 'Souza'),
	('Vitória Carvalho', '36', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '3 a 5 SM', 'Viúvo', 'MG', 'da Cunha'),
	('Valentina Correia', '70', 'Feminino', 'Fundamental Incompleto', 'Servidor Público', '< 1 SM', 'Divorciado', 'PA', 'Cavalcanti'),
	('Maria Alice das Neves', '64', 'Masculino', 'Médio Incompleto', 'Autônomo', '< 1 SM', 'Viúvo', 'RS', 'Campos'),
	('Marcos Vinicius Araújo', '46', 'Feminino', 'Médio Completo', 'Autônomo', '3 a 5 SM', 'Casado', 'PR', 'Cardoso'),
	('Sra. Emanuelly Nascimento', '27', 'Feminino', 'Superior Incompleto', 'Aposentado', '2 a 3 SM', 'Viúvo', 'MG', 'Souza'),
	('Bruna Nascimento', '49', 'Feminino', 'Médio Incompleto', 'Desempregado', '3 a 5 SM', 'Viúvo', 'MG', 'Campos de Ribeiro'),
	('Srta. Laís Almeida', '70', 'Masculino', 'Superior Incompleto', 'Aposentado', '< 1 SM', 'Viúvo', 'SP', 'Nascimento do Oeste'),
	('Bruna Rezende', '33', 'Feminino', 'Médio Incompleto', 'Aposentado', '2 a 3 SM', 'Casado', 'PA', 'Carvalho'),
	('Sophie Alves', '28', 'Feminino', 'Superior Incompleto', 'Autônomo', '1 a 2 SM', 'Divorciado', 'SP', 'da Paz de Correia'),
	('Benjamin Sales', '49', 'Feminino', 'Médio Incompleto', 'Empresário', '5 a 10 SM', 'Viúvo', 'MA', 'da Cruz'),
	('Leonardo Costela', '51', 'Masculino', 'Fundamental Incompleto', 'Autônomo', '1 a 2 SM', 'Casado', 'RS', 'Barbosa'),
	('Marina Castro', '55', 'Masculino', 'Fundamental Incompleto', 'Desempregado', '5 a 10 SM', 'Divorciado', 'MG', 'Castro'),
	('Dra. Maria Luiza da Rosa', '35', 'Feminino', 'Médio Completo', 'Desempregado', '5 a 10 SM', 'Solteiro', 'SP', 'Barros Paulista'),
	('Pietra Pires', '76', 'Masculino', 'Pós-graduação', 'Desempregado', '< 1 SM', 'Casado', 'PA', 'Duarte do Norte'),
	('Ryan Costa', '43', 'Masculino', 'Fundamental Completo', 'Autônomo', '> 10 SM', 'Divorciado', 'SP', 'Nunes'),
	('Dr. Fernando Rezende', '59', 'Masculino', 'Médio Incompleto', 'Empresário', '2 a 3 SM', 'Casado', 'CE', 'Campos'),
	('Vitor Gabriel Silva', '39', 'Feminino', 'Superior Incompleto', 'Empresário', '> 10 SM', 'Casado', 'CE', 'Farias'),
	('Luigi Lima', '79', 'Masculino', 'Superior Incompleto', 'Empresário', '2 a 3 SM', 'Casado', 'SP', 'Viana dos Dourados'),
	('Augusto Mendes', '39', 'Feminino', 'Médio Incompleto', 'Aposentado', '< 1 SM', 'Viúvo', 'MA', 'Martins'),
	('Carlos Eduardo Cavalcanti', '23', 'Masculino', 'Médio Completo', 'Aposentado', '2 a 3 SM', 'Viúvo', 'MG', 'Fogaça'),
	('Gabrielly da Paz', '65', 'Feminino', 'Superior Incompleto', 'Empresário', '3 a 5 SM', 'Divorciado', 'RJ', 'Nascimento'),
	('Ian Nascimento', '52', 'Masculino', 'Fundamental Completo', 'CLT', '1 a 2 SM', 'Viúvo', 'CE', 'Barbosa'),
	('André Teixeira', '45', 'Feminino', 'Fundamental Incompleto', 'CLT', '1 a 2 SM', 'Solteiro', 'RJ', 'da Paz de Minas'),
	('Maria Julia Lopes', '60', 'Feminino', 'Médio Incompleto', 'Autônomo', '1 a 2 SM', 'Solteiro', 'PR', 'Pereira'),
	('Ana da Rosa', '43', 'Masculino', 'Superior Incompleto', 'Servidor Público', '3 a 5 SM', 'Casado', 'PE', 'Jesus'),
	('Mariana Nogueira', '46', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '3 a 5 SM', 'Viúvo', 'PR', 'Moreira de Vieira'),
	('Luiz Otávio Silva', '68', 'Feminino', 'Superior Completo', 'Empresário', '< 1 SM', 'Casado', 'PA', 'da Cruz de da Costa'),
	('Laura Melo', '67', 'Masculino', 'Fundamental Incompleto', 'CLT', '3 a 5 SM', 'Solteiro', 'BA', 'da Paz das Flores'),
	('Thiago Novaes', '52', 'Feminino', 'Médio Completo', 'Servidor Público', '< 1 SM', 'Casado', 'PR', 'Lopes'),
	('Paulo Silveira', '41', 'Feminino', 'Médio Completo', 'Desempregado', '3 a 5 SM', 'Divorciado', 'PR', 'Cunha das Pedras'),
	('Daniel Cardoso', '78', 'Masculino', 'Fundamental Incompleto', 'Autônomo', '5 a 10 SM', 'Solteiro', 'SP', 'Pires'),
	('João Pedro Dias', '59', 'Masculino', 'Superior Completo', 'Empresário', '2 a 3 SM', 'Solteiro', 'PR', 'Cavalcanti de Costa'),
	('Joana das Neves', '22', 'Feminino', 'Pós-graduação', 'Autônomo', '1 a 2 SM', 'Viúvo', 'BA', 'Santos Verde'),
	('Renan Ferreira', '76', 'Feminino', 'Superior Incompleto', 'Servidor Público', '2 a 3 SM', 'Viúvo', 'PR', 'Alves de Vieira'),
	('Thales da Cruz', '18', 'Masculino', 'Pós-graduação', 'Desempregado', '3 a 5 SM', 'Divorciado', 'SP', 'Gomes da Prata'),
	('Lorena Pires', '21', 'Masculino', 'Médio Incompleto', 'Empresário', '5 a 10 SM', 'Solteiro', 'PE', 'Nascimento'),
	('Dr. Marcelo Silveira', '59', 'Masculino', 'Fundamental Completo', 'Empresário', '< 1 SM', 'Casado', 'PR', 'Souza do Campo'),
	('Maria Fernanda Almeida', '33', 'Feminino', 'Superior Incompleto', 'Autônomo', '2 a 3 SM', 'Divorciado', 'MG', 'Mendes'),
	('Joaquim Farias', '57', 'Feminino', 'Fundamental Incompleto', 'Empresário', '5 a 10 SM', 'Casado', 'MA', 'Moura das Pedras'),
	('Thomas Cavalcanti', '37', 'Feminino', 'Superior Completo', 'CLT', '3 a 5 SM', 'Viúvo', 'PA', 'da Rocha'),
	('Alícia Costa', '49', 'Feminino', 'Fundamental Completo', 'Aposentado', '3 a 5 SM', 'Casado', 'CE', 'Martins do Amparo'),
	('Sra. Marcela Duarte', '74', 'Feminino', 'Fundamental Completo', 'Desempregado', '> 10 SM', 'Divorciado', 'PA', 'Costa'),
	('Vinicius Martins', '29', 'Masculino', 'Médio Incompleto', 'Servidor Público', '> 10 SM', 'Viúvo', 'MA', 'Monteiro'),
	('Bruna Santos', '48', 'Feminino', 'Fundamental Completo', 'Desempregado', '> 10 SM', 'Divorciado', 'PE', 'Souza Paulista'),
	('João Pedro Duarte', '48', 'Masculino', 'Fundamental Completo', 'Aposentado', '< 1 SM', 'Viúvo', 'PR', 'Castro do Amparo'),
	('Luiz Otávio Costa', '71', 'Feminino', 'Superior Completo', 'Aposentado', '5 a 10 SM', 'Divorciado', 'PA', 'Ramos do Norte'),
	('Milena Pires', '39', 'Feminino', 'Fundamental Incompleto', 'Servidor Público', '1 a 2 SM', 'Casado', 'PA', 'Sales'),
	('Eduarda Barbosa', '21', 'Masculino', 'Superior Completo', 'CLT', '1 a 2 SM', 'Divorciado', 'BA', 'Gonçalves'),
	('Maria Vitória Costela', '52', 'Feminino', 'Fundamental Completo', 'Autônomo', '1 a 2 SM', 'Casado', 'SP', 'Alves de Souza'),
	('Valentina Freitas', '69', 'Masculino', 'Médio Completo', 'Aposentado', '2 a 3 SM', 'Divorciado', 'BA', 'da Cruz'),
	('Ian Viana', '55', 'Feminino', 'Médio Completo', 'Aposentado', '3 a 5 SM', 'Viúvo', 'PR', 'Barros'),
	('Davi Martins', '30', 'Masculino', 'Médio Completo', 'Servidor Público', '2 a 3 SM', 'Casado', 'RJ', 'Cardoso do Sul'),
	('Natália Gonçalves', '21', 'Masculino', 'Fundamental Incompleto', 'Autônomo', '> 10 SM', 'Casado', 'MG', 'Campos de Minas'),
	('Emanuella Ferreira', '66', 'Masculino', 'Médio Incompleto', 'CLT', '5 a 10 SM', 'Solteiro', 'MA', 'Caldeira'),
	('Heitor Fogaça', '55', 'Masculino', 'Médio Completo', 'Empresário', '2 a 3 SM', 'Divorciado', 'BA', 'Cardoso de Lopes'),
	('Rafaela Viana', '66', 'Masculino', 'Fundamental Completo', 'CLT', '> 10 SM', 'Divorciado', 'MG', 'das Neves de Almeida'),
	('Luiz Felipe Oliveira', '55', 'Masculino', 'Médio Incompleto', 'Empresário', '1 a 2 SM', 'Solteiro', 'PE', 'Moreira'),
	('Milena das Neves', '49', 'Masculino', 'Médio Incompleto', 'CLT', '3 a 5 SM', 'Divorciado', 'RS', 'Santos dos Dourados'),
	('Maria Fernanda Correia', '64', 'Masculino', 'Superior Incompleto', 'Empresário', '3 a 5 SM', 'Divorciado', 'CE', 'Rocha'),
	('Srta. Agatha Costa', '70', 'Masculino', 'Superior Completo', 'Aposentado', '> 10 SM', 'Divorciado', 'CE', 'Fernandes Verde'),
	('Ana Lima', '72', 'Feminino', 'Superior Incompleto', 'Aposentado', '5 a 10 SM', 'Casado', 'PR', 'Melo'),
	('Bruno Martins', '18', 'Masculino', 'Fundamental Incompleto', 'Aposentado', '3 a 5 SM', 'Solteiro', 'PE', 'da Cruz'),
	('Yuri da Luz', '53', 'Masculino', 'Fundamental Completo', 'Servidor Público', '< 1 SM', 'Solteiro', 'MG', 'Porto'),
	('Rafael Costela', '27', 'Masculino', 'Superior Completo', 'Desempregado', '2 a 3 SM', 'Solteiro', 'MA', 'Silveira'),
	('Sra. Laura Gonçalves', '78', 'Masculino', 'Médio Incompleto', 'CLT', '> 10 SM', 'Solteiro', 'PR', 'Duarte'),
	('Daniel Lopes', '78', 'Feminino', 'Pós-graduação', 'Aposentado', '3 a 5 SM', 'Viúvo', 'PR', 'Ramos Verde'),
	('Clara da Rosa', '52', 'Masculino', 'Fundamental Incompleto', 'CLT', '> 10 SM', 'Divorciado', 'MG', 'Nunes de Sales'),
	('Davi Silva', '78', 'Feminino', 'Pós-graduação', 'Desempregado', '2 a 3 SM', 'Solteiro', 'RS', 'Moreira'),
	('Nicolas Moreira', '36', 'Masculino', 'Médio Completo', 'Servidor Público', '5 a 10 SM', 'Casado', 'PR', 'Barros'),
	('Levi Duarte', '56', 'Masculino', 'Médio Completo', 'Servidor Público', '1 a 2 SM', 'Viúvo', 'MA', 'Sales'),
	('Mariana Pires', '51', 'Feminino', 'Pós-graduação', 'CLT', '3 a 5 SM', 'Divorciado', 'MA', 'Cardoso do Sul'),
	('Carolina da Costa', '50', 'Feminino', 'Pós-graduação', 'Servidor Público', '1 a 2 SM', 'Casado', 'CE', 'Mendes'),
	('João Gabriel Aragão', '74', 'Masculino', 'Superior Completo', 'Empresário', '5 a 10 SM', 'Viúvo', 'MG', 'Costela'),
	('Paulo Santos', '34', 'Masculino', 'Pós-graduação', 'CLT', '2 a 3 SM', 'Viúvo', 'BA', 'Viana'),
	('Maria Alice Nunes', '79', 'Feminino', 'Superior Completo', 'Desempregado', '< 1 SM', 'Viúvo', 'RJ', 'Freitas'),
	('Joaquim Moura', '40', 'Masculino', 'Superior Completo', 'Desempregado', '> 10 SM', 'Solteiro', 'PE', 'Ferreira de Santos'),
	('Evelyn Fernandes', '55', 'Feminino', 'Superior Incompleto', 'Empresário', '< 1 SM', 'Casado', 'PE', 'da Cunha de Moura'),
	('Marina Vieira', '20', 'Masculino', 'Médio Completo', 'Aposentado', '1 a 2 SM', 'Viúvo', 'BA', 'Farias do Amparo'),
	('Sophie Nogueira', '47', 'Feminino', 'Médio Incompleto', 'Aposentado', '> 10 SM', 'Divorciado', 'PA', 'da Conceição'),
	('Valentina Silva', '54', 'Feminino', 'Superior Incompleto', 'CLT', '1 a 2 SM', 'Casado', 'RS', 'Duarte'),
	('Caroline Costa', '36', 'Feminino', 'Fundamental Incompleto', 'Aposentado', '< 1 SM', 'Casado', 'PA', 'Viana de Minas'),
	('Laís Barros', '41', 'Feminino', 'Superior Completo', 'Aposentado', '1 a 2 SM', 'Casado', 'RJ', 'Pinto da Mata'),
	('Srta. Giovanna Araújo', '59', 'Feminino', 'Pós-graduação', 'CLT', '2 a 3 SM', 'Divorciado', 'MA', 'Monteiro de Novaes'),
	('Yasmin Costela', '36', 'Feminino', 'Superior Completo', 'Servidor Público', '< 1 SM', 'Viúvo', 'SP', 'Moraes'),
	('Ryan das Neves', '58', 'Feminino', 'Superior Incompleto', 'Autônomo', '> 10 SM', 'Viúvo', 'PR', 'Gonçalves'),
	('Matheus Peixoto', '57', 'Masculino', 'Pós-graduação', 'Empresário', '5 a 10 SM', 'Solteiro', 'SP', 'Aragão da Praia'),
	('Dr. Luiz Miguel Lima', '32', 'Masculino', 'Fundamental Completo', 'Servidor Público', '3 a 5 SM', 'Divorciado', 'SP', 'Correia'),
	('Melissa das Neves', '48', 'Feminino', 'Médio Completo', 'Desempregado', '1 a 2 SM', 'Solteiro', 'RS', 'Fogaça de Moura'),
	('Daniela Freitas', '75', 'Masculino', 'Médio Completo', 'Autônomo', '1 a 2 SM', 'Viúvo', 'RS', 'Rezende do Galho'),
	('Maria Fernanda Cardoso', '52', 'Masculino', 'Médio Incompleto', 'CLT', '1 a 2 SM', 'Divorciado', 'PE', 'Cardoso'),
	('Maria da Mata', '19', 'Masculino', 'Superior Completo', 'Empresário', '3 a 5 SM', 'Solteiro', 'MA', 'Castro'),
	('Gustavo Henrique Cardoso', '67', 'Feminino', 'Médio Incompleto', 'Aposentado', '< 1 SM', 'Casado', 'RJ', 'Ribeiro'),
	('João Pedro Santos', '66', 'Feminino', 'Fundamental Incompleto', 'Empresário', '3 a 5 SM', 'Solteiro', 'PA', 'Moura'),
	('Eduarda Teixeira', '56', 'Feminino', 'Superior Completo', 'Servidor Público', '3 a 5 SM', 'Divorciado', 'CE', 'Jesus'),
	('Rebeca da Luz', '58', 'Feminino', 'Superior Incompleto', 'Servidor Público', '> 10 SM', 'Viúvo', 'CE', 'Peixoto Verde'),
	('Heitor Jesus', '32', 'Feminino', 'Superior Completo', 'Desempregado', '1 a 2 SM', 'Casado', 'CE', 'da Paz'),
	('Sr. Henrique Fernandes', '32', 'Feminino', 'Médio Incompleto', 'Empresário', '1 a 2 SM', 'Solteiro', 'PA', 'Rocha'),
	('Maria Julia Santos', '37', 'Masculino', 'Superior Incompleto', 'Autônomo', '5 a 10 SM', 'Viúvo', 'PA', 'da Cunha'),
	('Luiz Miguel Cunha', '53', 'Masculino', 'Fundamental Completo', 'Aposentado', '1 a 2 SM', 'Viúvo', 'MG', 'Porto'),
	('João Gabriel Pereira', '45', 'Masculino', 'Pós-graduação', 'CLT', '1 a 2 SM', 'Divorciado', 'PE', 'Farias das Flores'),
	('Luiza Pereira', '51', 'Feminino', 'Médio Completo', 'Servidor Público', '5 a 10 SM', 'Viúvo', 'PE', 'Carvalho de Pinto'),
	('Alexia Lopes', '56', 'Masculino', 'Médio Completo', 'Desempregado', '3 a 5 SM', 'Solteiro', 'MG', 'Barros'),
	('Dra. Gabrielly Carvalho', '19', 'Masculino', 'Médio Completo', 'Servidor Público', '1 a 2 SM', 'Divorciado', 'CE', 'da Costa'),
	('Nicolas Campos', '20', 'Masculino', 'Fundamental Incompleto', 'CLT', '< 1 SM', 'Casado', 'BA', 'Vieira'),
	('Enzo Gabriel Gomes', '21', 'Masculino', 'Superior Incompleto', 'Desempregado', '> 10 SM', 'Solteiro', 'CE', 'Freitas'),
	('Lucas da Luz', '35', 'Masculino', 'Fundamental Completo', 'Servidor Público', '5 a 10 SM', 'Viúvo', 'MA', 'Caldeira'),
	('Ana Laura Farias', '74', 'Masculino', 'Superior Completo', 'CLT', '2 a 3 SM', 'Viúvo', 'BA', 'Farias'),
	('Rafaela Santos', '78', 'Feminino', 'Pós-graduação', 'Desempregado', '1 a 2 SM', 'Solteiro', 'RJ', 'Silveira de Cardoso'),
	('Dra. Ana Luiza Nunes', '46', 'Feminino', 'Médio Incompleto', 'CLT', '1 a 2 SM', 'Casado', 'MG', 'Nogueira do Norte'),
	('Ryan Novaes', '45', 'Feminino', 'Fundamental Completo', 'Aposentado', '3 a 5 SM', 'Divorciado', 'PR', 'Gonçalves do Campo'),
	('João Silva', '52', 'Feminino', 'Fundamental Incompleto', 'Autônomo', '> 10 SM', 'Solteiro', 'MG', 'Novaes dos Dourados'),
	('Natália da Luz', '49', 'Feminino', 'Médio Incompleto', 'Aposentado', '1 a 2 SM', 'Casado', 'MG', 'da Costa'),
	('Dra. Maria Luiza Gomes', '51', 'Feminino', 'Superior Incompleto', 'Servidor Público', '1 a 2 SM', 'Viúvo', 'MG', 'da Mata'),
	('Rodrigo Melo', '30', 'Feminino', 'Médio Incompleto', 'Desempregado', '> 10 SM', 'Viúvo', 'SP', 'Caldeira'),
	('Nicolas Almeida', '60', 'Feminino', 'Médio Incompleto', 'Servidor Público', '> 10 SM', 'Divorciado', 'MA', 'Pinto Grande'),
	('Luiz Otávio Moura', '40', 'Masculino', 'Pós-graduação', 'CLT', '5 a 10 SM', 'Divorciado', 'MA', 'Pinto'),
	('Gustavo Henrique da Cruz', '64', 'Masculino', 'Médio Incompleto', 'Servidor Público', '> 10 SM', 'Divorciado', 'PR', 'Mendes das Flores'),
	('Pietro Nunes', '45', 'Feminino', 'Médio Incompleto', 'Empresário', '3 a 5 SM', 'Viúvo', 'RS', 'Rezende'),
	('Letícia Melo', '80', 'Masculino', 'Fundamental Incompleto', 'Servidor Público', '< 1 SM', 'Divorciado', 'RJ', 'Silveira dos Dourados'),
	('Ana Luiza Rodrigues', '72', 'Feminino', 'Fundamental Incompleto', 'Empresário', '> 10 SM', 'Casado', 'CE', 'Rocha'),
	('André Ramos', '50', 'Masculino', 'Fundamental Incompleto', 'Autônomo', '2 a 3 SM', 'Solteiro', 'PA', 'Moreira'),
	('Ana Costa', '77', 'Masculino', 'Superior Incompleto', 'Aposentado', '1 a 2 SM', 'Viúvo', 'PE', 'da Rocha de Rezende'),
	('Nicolas da Rocha', '77', 'Masculino', 'Médio Incompleto', 'CLT', '< 1 SM', 'Casado', 'MA', 'Moura'),
	('Kevin das Neves', '50', 'Feminino', 'Superior Completo', 'Aposentado', '2 a 3 SM', 'Casado', 'MA', 'da Cunha'),
	('Gabriela Santos', '31', 'Feminino', 'Médio Incompleto', 'Autônomo', '< 1 SM', 'Casado', 'RS', 'Monteiro do Campo'),
	('Yuri Campos', '27', 'Masculino', 'Fundamental Incompleto', 'Autônomo', '3 a 5 SM', 'Viúvo', 'PE', 'da Cunha'),
	('Ana Ramos', '49', 'Masculino', 'Médio Completo', 'Autônomo', '> 10 SM', 'Casado', 'MA', 'Pereira da Prata'),
	('Valentina da Mota', '74', 'Masculino', 'Fundamental Completo', 'Empresário', '2 a 3 SM', 'Casado', 'SP', 'Cavalcanti'),
	('Sr. Juan Lopes', '46', 'Masculino', 'Superior Incompleto', 'Aposentado', '5 a 10 SM', 'Solteiro', 'BA', 'Moura'),
	('Elisa da Mata', '56', 'Masculino', 'Superior Completo', 'Servidor Público', '2 a 3 SM', 'Viúvo', 'PR', 'Araújo do Amparo'),
	('Bryan da Rosa', '66', 'Feminino', 'Médio Completo', 'Servidor Público', '1 a 2 SM', 'Viúvo', 'RS', 'Peixoto'),
	('Otávio Cunha', '45', 'Masculino', 'Pós-graduação', 'Servidor Público', '< 1 SM', 'Solteiro', 'MG', 'Barbosa da Praia'),
	('Letícia Ribeiro', '57', 'Masculino', 'Fundamental Incompleto', 'Aposentado', '> 10 SM', 'Casado', 'MA', 'Oliveira Alegre'),
	('Elisa Aragão', '77', 'Masculino', 'Médio Completo', 'Empresário', '5 a 10 SM', 'Casado', 'CE', 'da Mota de Campos'),
	('Dra. Maria Julia Vieira', '73', 'Feminino', 'Pós-graduação', 'CLT', '1 a 2 SM', 'Viúvo', 'BA', 'da Conceição'),
	('Ana Luiza Oliveira', '40', 'Masculino', 'Médio Completo', 'Servidor Público', '1 a 2 SM', 'Solteiro', 'MG', 'Caldeira de Goiás'),
	('Carlos Eduardo das Neves', '69', 'Masculino', 'Pós-graduação', 'Empresário', '2 a 3 SM', 'Viúvo', 'SP', 'Costela das Flores'),
	('Gabriela Freitas', '51', 'Masculino', 'Fundamental Completo', 'CLT', '> 10 SM', 'Solteiro', 'PR', 'Fernandes do Amparo'),
	('Sr. Davi Costela', '43', 'Feminino', 'Fundamental Completo', 'Servidor Público', '1 a 2 SM', 'Divorciado', 'BA', 'Carvalho'),
	('João Vitor da Rocha', '56', 'Feminino', 'Superior Completo', 'Autônomo', '2 a 3 SM', 'Divorciado', 'PR', 'Vieira'),
	('Maria Fernanda Pinto', '79', 'Masculino', 'Fundamental Incompleto', 'Desempregado', '2 a 3 SM', 'Viúvo', 'SP', 'da Cruz de da Rosa'),
	('Luigi Barbosa', '80', 'Masculino', 'Pós-graduação', 'Autônomo', '3 a 5 SM', 'Viúvo', 'MA', 'Silva'),
	('Marcelo Monteiro', '42', 'Masculino', 'Superior Incompleto', 'Desempregado', '< 1 SM', 'Solteiro', 'BA', 'Costa do Norte'),
	('Miguel Silveira', '78', 'Masculino', 'Médio Incompleto', 'Servidor Público', '1 a 2 SM', 'Casado', 'RJ', 'Ferreira de Minas'),
	('Renan Barros', '57', 'Masculino', 'Médio Completo', 'Aposentado', '3 a 5 SM', 'Casado', 'CE', 'Fernandes do Oeste'),
	('Pietra Duarte', '78', 'Masculino', 'Superior Completo', 'Servidor Público', '1 a 2 SM', 'Solteiro', 'MA', 'da Mata da Prata'),
	('Esther Campos', '20', 'Masculino', 'Fundamental Incompleto', 'CLT', '1 a 2 SM', 'Divorciado', 'SP', 'da Rosa'),
	('Ana Duarte', '33', 'Masculino', 'Fundamental Incompleto', 'CLT', '5 a 10 SM', 'Viúvo', 'RJ', 'Souza'),
	('Dr. João Pedro Teixeira', '40', 'Feminino', 'Médio Completo', 'CLT', '2 a 3 SM', 'Casado', 'BA', 'Souza'),
	('Davi Lucas Ribeiro', '71', 'Feminino', 'Fundamental Incompleto', 'Desempregado', '3 a 5 SM', 'Solteiro', 'MA', 'Souza'),
	('Carlos Eduardo Sales', '45', 'Masculino', 'Superior Incompleto', 'Desempregado', '< 1 SM', 'Viúvo', 'PE', 'Almeida'),
	('Mariane da Mota', '55', 'Feminino', 'Médio Incompleto', 'CLT', '3 a 5 SM', 'Solteiro', 'MA', 'Correia'),
	('Maria Julia Correia', '37', 'Masculino', 'Médio Incompleto', 'Autônomo', '2 a 3 SM', 'Viúvo', 'PE', 'Ramos'),
	('Luiza Rodrigues', '28', 'Masculino', 'Fundamental Completo', 'Empresário', '2 a 3 SM', 'Solteiro', 'PE', 'Ramos'),
	('Leonardo Freitas', '77', 'Feminino', 'Fundamental Completo', 'CLT', '5 a 10 SM', 'Casado', 'RS', 'da Costa do Oeste'),
	('Agatha da Mota', '57', 'Masculino', 'Médio Incompleto', 'Aposentado', '2 a 3 SM', 'Divorciado', 'CE', 'Gomes'),
	('Maria Alice Mendes', '48', 'Masculino', 'Pós-graduação', 'Servidor Público', '3 a 5 SM', 'Solteiro', 'PE', 'Caldeira'),
	('Luana Ramos', '32', 'Masculino', 'Fundamental Completo', 'Aposentado', '5 a 10 SM', 'Solteiro', 'RJ', 'da Costa'),
	('Natália Sales', '63', 'Masculino', 'Superior Completo', 'Empresário', '> 10 SM', 'Solteiro', 'RS', 'Dias'),
	('Enrico da Mata', '70', 'Feminino', 'Médio Completo', 'Autônomo', '2 a 3 SM', 'Divorciado', 'BA', 'Moraes das Pedras'),
	('Calebe Sales', '24', 'Feminino', 'Fundamental Incompleto', 'Autônomo', '1 a 2 SM', 'Casado', 'MA', 'da Mata de Goiás'),
	('Sophie Cardoso', '33', 'Feminino', 'Médio Completo', 'Autônomo', '5 a 10 SM', 'Casado', 'RS', 'Moura da Prata'),
	('João Felipe Farias', '18', 'Masculino', 'Médio Incompleto', 'CLT', '< 1 SM', 'Solteiro', 'PE', 'Costela'),
	('João Felipe Novaes', '65', 'Feminino', 'Fundamental Incompleto', 'Aposentado', '1 a 2 SM', 'Solteiro', 'BA', 'Azevedo'),
	('João Gabriel Rodrigues', '59', 'Masculino', 'Médio Incompleto', 'CLT', '3 a 5 SM', 'Solteiro', 'BA', 'Gonçalves do Amparo'),
	('Yago das Neves', '78', 'Masculino', 'Médio Completo', 'Empresário', '1 a 2 SM', 'Solteiro', 'PA', 'Caldeira'),
	('Sr. Luiz Felipe Silveira', '30', 'Feminino', 'Pós-graduação', 'Aposentado', '2 a 3 SM', 'Divorciado', 'MG', 'Barbosa de Goiás'),
	('Srta. Manuela Oliveira', '23', 'Masculino', 'Pós-graduação', 'CLT', '< 1 SM', 'Casado', 'PR', 'da Mota das Pedras'),
	('Olivia Gomes', '36', 'Feminino', 'Superior Incompleto', 'Aposentado', '< 1 SM', 'Casado', 'MG', 'Dias'),
	('Dr. João Gabriel da Mata', '48', 'Feminino', 'Médio Incompleto', 'Desempregado', '> 10 SM', 'Divorciado', 'MA', 'Costa do Amparo'),
	('João Guilherme Campos', '24', 'Masculino', 'Médio Completo', 'CLT', '< 1 SM', 'Viúvo', 'BA', 'Moreira'),
	('Cecília Ribeiro', '45', 'Masculino', 'Médio Incompleto', 'Desempregado', '> 10 SM', 'Casado', 'BA', 'Ramos'),
	('Gustavo das Neves', '51', 'Masculino', 'Médio Incompleto', 'Desempregado', '5 a 10 SM', 'Solteiro', 'PA', 'Cunha'),
	('Ana Vitória Mendes', '71', 'Masculino', 'Médio Incompleto', 'Servidor Público', '1 a 2 SM', 'Solteiro', 'MA', 'Carvalho do Campo'),
	('Eloah Ramos', '18', 'Feminino', 'Superior Incompleto', 'Aposentado', '1 a 2 SM', 'Divorciado', 'RS', 'Gomes'),
	('Otávio Pires', '37', 'Feminino', 'Médio Incompleto', 'Autônomo', '3 a 5 SM', 'Viúvo', 'MG', 'da Cruz de Goiás'),
	('Daniel Ribeiro', '39', 'Feminino', 'Pós-graduação', 'CLT', '3 a 5 SM', 'Solteiro', 'PR', 'Martins de Goiás'),
	('Sabrina Gomes', '56', 'Feminino', 'Pós-graduação', 'Empresário', '2 a 3 SM', 'Casado', 'SP', 'Correia'),
	('Nathan Aragão', '66', 'Feminino', 'Fundamental Completo', 'CLT', '< 1 SM', 'Solteiro', 'BA', 'Carvalho'),
	('Valentina Correia', '65', 'Feminino', 'Médio Incompleto', 'Empresário', '2 a 3 SM', 'Viúvo', 'SP', 'Alves de da Mota'),
	('Eloah Gomes', '68', 'Feminino', 'Fundamental Completo', 'Autônomo', '2 a 3 SM', 'Solteiro', 'RJ', 'Ribeiro'),
	('Alice Cardoso', '26', 'Masculino', 'Fundamental Incompleto', 'Servidor Público', '1 a 2 SM', 'Solteiro', 'PA', 'Azevedo do Campo'),
	('André Rocha', '60', 'Feminino', 'Médio Incompleto', 'Empresário', '5 a 10 SM', 'Viúvo', 'PR', 'da Mata'),
	('Lara Novaes', '23', 'Feminino', 'Pós-graduação', 'Desempregado', '> 10 SM', 'Divorciado', 'MG', 'Aragão'),
	('Ana Julia da Rosa', '40', 'Masculino', 'Superior Completo', 'Empresário', '> 10 SM', 'Divorciado', 'RS', 'Cardoso do Amparo'),
	('Diego Pinto', '39', 'Masculino', 'Fundamental Completo', 'Desempregado', '> 10 SM', 'Viúvo', 'CE', 'Moraes de Costela'),
	('Dr. Alexandre Pereira', '57', 'Masculino', 'Médio Completo', 'Desempregado', '5 a 10 SM', 'Viúvo', 'RS', 'Moreira do Sul'),
	('Sr. Bernardo Castro', '77', 'Masculino', 'Pós-graduação', 'Servidor Público', '> 10 SM', 'Casado', 'MA', 'Silva de Minas'),
	('Srta. Heloísa Rodrigues', '71', 'Feminino', 'Fundamental Completo', 'Autônomo', '3 a 5 SM', 'Divorciado', 'RS', 'Castro de Ribeiro'),
	('João Pedro Melo', '56', 'Masculino', 'Médio Completo', 'CLT', '5 a 10 SM', 'Casado', 'SP', 'Nunes'),
	('Isaac Costela', '64', 'Feminino', 'Médio Incompleto', 'Servidor Público', '2 a 3 SM', 'Casado', 'MA', 'Oliveira de Moreira'),
	('Ian da Mota', '32', 'Masculino', 'Superior Completo', 'Aposentado', '1 a 2 SM', 'Viúvo', 'RJ', 'Farias de Nascimento'),
	('Srta. Helena Silveira', '65', 'Masculino', 'Superior Completo', 'Aposentado', '2 a 3 SM', 'Casado', 'MG', 'da Paz'),
	('Sr. Arthur Teixeira', '50', 'Feminino', 'Superior Completo', 'Desempregado', '< 1 SM', 'Casado', 'SP', 'Moraes'),
	('Bryan Sales', '28', 'Masculino', 'Pós-graduação', 'CLT', '5 a 10 SM', 'Viúvo', 'SP', 'Vieira de Fogaça'),
	('Caio Silva', '19', 'Masculino', 'Superior Completo', 'Autônomo', '3 a 5 SM', 'Solteiro', 'PE', 'da Luz'),
	('Luiz Gustavo da Paz', '38', 'Masculino', 'Médio Incompleto', 'Aposentado', '> 10 SM', 'Solteiro', 'CE', 'Melo'),
	('Yuri Araújo', '64', 'Masculino', 'Médio Incompleto', 'Autônomo', '2 a 3 SM', 'Solteiro', 'BA', 'Dias'),
	('Srta. Nicole Barros', '49', 'Masculino', 'Superior Incompleto', 'Servidor Público', '5 a 10 SM', 'Casado', 'MA', 'Nogueira do Norte'),
	('Carlos Eduardo Ferreira', '62', 'Feminino', 'Médio Completo', 'CLT', '> 10 SM', 'Viúvo', 'BA', 'Barros'),
	('Rafael Carvalho', '79', 'Feminino', 'Superior Incompleto', 'Desempregado', '3 a 5 SM', 'Divorciado', 'MA', 'Costela do Norte'),
	('Vinicius Silva', '61', 'Feminino', 'Médio Incompleto', 'Aposentado', '1 a 2 SM', 'Casado', 'RS', 'Caldeira de Costa'),
	('Brenda Barros', '56', 'Masculino', 'Fundamental Incompleto', 'Aposentado', '< 1 SM', 'Casado', 'SP', 'Correia'),
	('Pedro Miguel Cunha', '66', 'Masculino', 'Pós-graduação', 'CLT', '1 a 2 SM', 'Casado', 'RS', 'Moura das Flores'),
	('Maria Sophia Melo', '37', 'Feminino', 'Pós-graduação', 'CLT', '1 a 2 SM', 'Solteiro', 'PR', 'Ferreira Paulista'),
	('Mariane Lima', '43', 'Masculino', 'Médio Completo', 'Desempregado', '5 a 10 SM', 'Viúvo', 'RS', 'Melo'),
	('Beatriz Ferreira', '46', 'Feminino', 'Fundamental Incompleto', 'Empresário', '> 10 SM', 'Casado', 'MG', 'Ramos'),
	('João Guilherme Nogueira', '61', 'Feminino', 'Médio Completo', 'Autônomo', '1 a 2 SM', 'Divorciado', 'MA', 'Teixeira'),
	('Dr. Erick da Mota', '20', 'Feminino', 'Médio Incompleto', 'Empresário', '5 a 10 SM', 'Viúvo', 'PA', 'Barros'),
	('Marcela Peixoto', '32', 'Masculino', 'Superior Completo', 'Autônomo', '1 a 2 SM', 'Solteiro', 'PA', 'Azevedo'),
	('Sofia Fernandes', '66', 'Masculino', 'Fundamental Incompleto', 'CLT', '1 a 2 SM', 'Casado', 'SP', 'da Conceição'),
	('Lara Carvalho', '32', 'Masculino', 'Superior Incompleto', 'Desempregado', '3 a 5 SM', 'Divorciado', 'MA', 'Araújo do Norte'),
	('Bruna Moura', '53', 'Feminino', 'Fundamental Completo', 'Autônomo', '5 a 10 SM', 'Viúvo', 'SP', 'Dias da Mata'),
	('Emanuelly Alves', '32', 'Masculino', 'Fundamental Incompleto', 'Desempregado', '2 a 3 SM', 'Viúvo', 'RJ', 'da Conceição do Sul'),
	('Sabrina Martins', '28', 'Feminino', 'Fundamental Completo', 'Desempregado', '3 a 5 SM', 'Casado', 'MA', 'Peixoto'),
	('Diogo Cavalcanti', '77', 'Feminino', 'Superior Completo', 'Autônomo', '> 10 SM', 'Viúvo', 'PE', 'Sales do Oeste'),
	('Isaac Freitas', '33', 'Masculino', 'Fundamental Incompleto', 'Servidor Público', '< 1 SM', 'Divorciado', 'PA', 'Souza'),
	('Sra. Evelyn Costela', '70', 'Masculino', 'Fundamental Incompleto', 'Autônomo', '1 a 2 SM', 'Divorciado', 'BA', 'Freitas Paulista'),
	('Davi Luiz Gomes', '35', 'Masculino', 'Pós-graduação', 'Desempregado', '3 a 5 SM', 'Viúvo', 'MA', 'Barbosa'),
	('Alice Peixoto', '55', 'Feminino', 'Superior Completo', 'CLT', '1 a 2 SM', 'Viúvo', 'MA', 'das Neves da Mata');